language: android

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services

jdk:
  - oraclejdk8

script:
  - ./gradlew testDebugUnitTest

notifications:
  email: false
